version: "3.3"
services:
  # Backend
  backend:
    image: balloon-game-server:latest
    container_name: balloon-game-server
    restart: unless-stopped
    networks:
      - stnkv-network
  # Web server
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - stnkv-network
    volumes:
      - ./nginx:/etc/nginx/conf.d

networks:
  stnkv-network:
    driver: bridge