name: Publish and deploy docker image
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/balloon-game-server
          VERSION=${GITHUB_REF#refs/*/}
          TAGS="${TAGS},${GHCR_IMAGE}:${VERSION},${GHCR_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ghcr_image::${GHCR_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run playbook for deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-playbook.yml
          directory: ./ansible/
          key: ${{secrets.SSH_RSA_KEY}}
          inventory: |
            [prod]
            ${{secrets.IP_ADDR_PROD}}
          options:
            --extra-vars "GHCR_USERNAME=${{ github.repository_owner }} GHCR_PASSWORD=${{ secrets.CR_PAT }}"